# Generated by Django 5.2.6 on 2025-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'InProgress'), (2, 'Completed')], default=0, max_length=2),
        ),
    ]
